<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="TC_04_CreateAccountTest"
           tests="2"
           failures="1"
           errors="0"
           skipped="0"
           time="10.686">
  <properties />
            <testcase name="CreateRandomAccTest" time="4.440" classname="com.ugapp.testcases.TC_04_CreateAccountTest">
                <failure type="java.lang.NoSuchMethodError"
                  message="&apos;void org.apache.commons.compress.archivers.zip.ZipArchiveOutputStream.putArchiveEntry(org.apache.commons.compress.archivers.zip.ZipArchiveEntry)&apos;"
              >
<![CDATA[java.lang.NoSuchMethodError: 'void org.apache.commons.compress.archivers.zip.ZipArchiveOutputStream.putArchiveEntry(org.apache.commons.compress.archivers.zip.ZipArchiveEntry)'
  org.apache.poi.openxml4j.opc.internal.ZipContentTypeManager.saveImpl(ZipContentTypeManager.java:65)
  org.apache.poi.openxml4j.opc.internal.ContentTypeManager.save(ContentTypeManager.java:450)
  org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:608)
  org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1532)
  org.apache.poi.ooxml.POIXMLDocument.write(POIXMLDocument.java:227)
  com.ugapp.base.Page.saveReport(Page.java:560)
  com.ugapp.pages.CreateAccountPage.CreateRandomAcc(CreateAccountPage.java:382)
  com.ugapp.testcases.TC_04_CreateAccountTest.CreateRandomAccTest(TC_04_CreateAccountTest.java:84)
  java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  java.base/java.lang.reflect.Method.invoke(Method.java:578)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
  org.testng.TestRunner.privateRun(TestRunner.java:756)
  org.testng.TestRunner.run(TestRunner.java:610)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
  org.testng.SuiteRunner.run(SuiteRunner.java:289)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
  org.testng.TestNG.runSuites(TestNG.java:1133)
  org.testng.TestNG.run(TestNG.java:1104)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="verifyCreateAcc" time="6.246" classname="com.ugapp.testcases.TC_04_CreateAccountTest" />
      
</testsuite>
